### ISSUE TITLE
Problem with switch2pos and arduino leonardo and mega

### ISSUE THREAD

**Issue by shopiK** [dcs-bios/dcs-bios-arduino-library#21] opened 2015-06-12 05:13 UTC
Hello, I'm very interested in your project. I've got some problem with arduino leonardo same as mega.

When i try to connect arduino via dcs bios everything works properly. I can light up LEDs, drive lcddisplay and use action buttons. But when i add to code something from reference witch 2position switches - script stops responding. Led stops working, lcd stops refreshing and added switch no responding, etc...

Please help! 
Greeting, shopiK

#include "DcsBios.h"
#include "Servo.h"
#include "LiquidCrystal.h"
LiquidCrystal lcd(7,6,5,4,3,2);

/**** Make your changes after this line ****/
DcsBios::LED lowRpmInd(0x1416, 0x0080, 13);
DcsBios::LED masterCautionInd(0x1416, 0x0100, 9);
DcsBios::Switch2Pos batSw("BAT_SW", 45);  //<<<<<<<<< THIS LINE GENERATE PROBLEM
//DcsBios::Switch2Pos starterGenSw("STARTER_GEN_SW", 11);   //<<<<<THIS LINE AS BOVE
//DcsBios::ActionButton batSwToggle("BAT_SW", "TOGGLE", 45);  //<<<<THIS LINE works fine

void onRaltDisplayChange(char* newValue) {
    lcd.setCursor(0,1);
    lcd.print(newValue);
}

void onVhfcommFreqChange(char* newValue) {
    lcd.setCursor(0,0);
    lcd.print(newValue);
}
DcsBios::StringBuffer<7> vhfcommFreqBuffer(0x14d4, onVhfcommFreqChange);

void onUhfFreqChange(char* newValue) {
    lcd.setCursor(9,0);
    lcd.print(newValue);
}
DcsBios::StringBuffer<6> uhfFreqBuffer(0x14e2, onUhfFreqChange);

void onVhfnavFreqChange(char* newValue) {
    lcd.setCursor(9,1);
    lcd.print(newValue);
}
DcsBios::StringBuffer<6> vhfnavFreqBuffer(0x14f0, onVhfnavFreqChange);

/**** In most cases, you do not have to change anything below this line ****/
/* Instantiate a ProtocolParser object to parse the DCS-BIOS export stream */
DcsBios::ProtocolParser parser;

void setup() {
  pinMode(45, INPUT);
  Serial.begin(9600);
  lcd.begin(16,2);
  lcd.clear();
  
  }

void loop() {
  // feed incoming data to the parser
  while (Serial.available()) {
      parser.processChar(Serial.read());
  }

  // poll inputs
//
  DcsBios::PollingInput::pollInputs();
}

void sendDcsBiosMessage(const char* msg, const char* arg) {
  Serial.write(msg);
  Serial.write(' ');
  Serial.write(arg);
  Serial.write('\n');
}

void onDcsBiosWrite(unsigned int address, unsigned int value) {
if (address == 0x040a) {
unsigned int hdgDegValue = (value & 0x01ff) >> 0;
lcd.setCursor(1,1);
lcd.print(hdgDegValue);
}

}

**Comment by jboecker** [comment] 2015-06-22 07:46
This is a duplicate of dcs-bios/dcs-bios#64.

**Closed by jboecker** 2015-06-22 07:46 UTC
